"""add_provisioning_logs_and_installation_progress

Revision ID: 7c4f526d09bc
Revises: 38f1c2becf38
Create Date: 2026-07-19 11:39:19.724973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c4f526d09bc'
down_revision: Union[str, None] = '38f1c2becf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provisioning_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('box_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['boxes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provisioning_logs_box_id'), 'provisioning_logs', ['box_id'], unique=False)
    op.add_column('boxes', sa.Column('installation_progress', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boxes', 'installation_progress')
    op.drop_index(op.f('ix_provisioning_logs_box_id'), table_name='provisioning_logs')
    op.drop_table('provisioning_logs')
    # ### end Alembic commands ###
